name: "base eks deploy action"
description: "used for eks deploys"
branding:
  icon: "anchor"
  color: "blue"
inputs:
  command:
    description: "Your command (kubectl or helm)"
    required: true
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  args: []
